from tkinter import *

multi_sent=Tk()
multi_sent.minsize(500,500)

multi_sent.rowconfigure(0,weight=1)
multi_sent.rowconfigure(1,weight=1)
multi_sent.rowconfigure(2,weight=1)
multi_sent.rowconfigure(3,weight=1)
multi_sent.rowconfigure(4,weight=1)
multi_sent.rowconfigure(5,weight=1)
multi_sent.rowconfigure(6,weight=1)
multi_sent.rowconfigure(7,weight=1)
multi_sent.rowconfigure(8,weight=1)
multi_sent.rowconfigure(9,weight=1)
multi_sent.rowconfigure(10,weight=1)
multi_sent.columnconfigure(0,weight=1)
multi_sent.columnconfigure(1,weight=1)

def get_values():
    sent1=sent1.get()
    sent2=sent2.get()
    sent3=sent3.get()
    sent4=sent4.get()
    sent5=sent5.get()
    sent6=sent6.get()
    sent7=sent7.get()
    sent8=sent8.get()
    sent9=sent9.get()
    sent10=sent10.get()

#creating different widgets
top_label=Label(multi_sent,text="Enter the sentences in following boxes: ")
sent1=Entry(multi_sent)
sent2=Entry(multi_sent)
sent3=Entry(multi_sent)
sent4=Entry(multi_sent)
sent5=Entry(multi_sent)
sent6=Entry(multi_sent)
sent7=Entry(multi_sent)
sent8=Entry(multi_sent)
sent9=Entry(multi_sent)
sent10=Entry(multi_sent)
submit_button=Button(multi_sent,text="Submit")

#packing the widgets using grid
top_label.grid(row=0,column=0)
sent1.grid(row=1,column=0)
sent2.grid(row=2,column=0)
sent3.grid(row=3,column=0)
sent4.grid(row=4,column=0)
sent5.grid(row=5,column=0)
sent6.grid(row=6,column=0)
sent7.grid(row=7,column=0)
sent8.grid(row=8,column=0)
sent9.grid(row=9,column=0)
sent10.grid(row=10,column=0)
submit_button.grid(row=11,column=0)

multi_sent.mainloop()